### ISSUE TITLE
Github actions fail except for main branch

### ISSUE THREAD

**Issue by 2Daeyoung** [Pluralith/actions#13]
Hello ~
There is something weird situation when I PR feature branch.

I made workflow for feature branch to comment same as main branch but fails every times except for main branch.

error message :
→ Authentication
  ✔ API key is valid, you are authenticated!
→ Project Setup
  ✔ Existing Org Found
  ✔ Existing Project Found
→ Plan
  ✔ Execution Plan Generated
  ✔ Plan Cache Created
  ✔ Secrets Stripped
  - Cost Calculation Skipped
→ Graph
  ✔ Diagram Generated
  ✘ Posting Run To Pluralith Dashboard Failed
posting run for PR comment failed -> PostGraph: request failed -> LogRun: map[code:400 error:map[] message:Logging run failed]

Can you check this? CLI version is latest version.

**Comment by DanThePutzer** [comment]
Hi @2Daeyoung thanks for reporting!

This seems to be a related issue to the one [you reported on the CLI repo](https://github.com/Pluralith/pluralith-cli/issues/89). I'll look into it and report back here when I find something!

**Comment by 2Daeyoung** [comment]
Same for
https://github.com/Pluralith/pluralith-cli/issues/89
